---
# Kubernetes Configuration - LATEST versions
pod_network_cidr: "10.244.0.0/16"
service_subnet: "10.96.0.0/12"
kubernetes_api_server_advertise_address: "192.168.70.211"
kubernetes_api_server_bind_port: 16443
k8s_cluster_name: "kharrinhao"
disable_swap: true
container_runtime: containerd
cgroup_driver: systemd

# Phase 1: Core Infrastructure Configuration
# Flannel CNI Configuration (Simple and Reliable)
cni_plugin: flannel
flannel_version: "latest"
flannel_manifest_url: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
flannel_namespace: "kube-flannel"

# cert-manager Configuration  
cert_manager_version: "v1.16.2"
cert_manager_namespace: "cert-manager"

# Ingress NGINX Configuration
ingress_nginx_version: "4.12.0"
ingress_nginx_namespace: "ingress-nginx"

# Domain Configuration (for local development)
base_domain: "k8s.local"
ingress_domains:
  - login.k8s.local
  - auth.k8s.local
  - dashboard.k8s.local
  - grafana.k8s.local
  - argocd.k8s.local

# Port forwarding (for SSH tunneling)
port_forward_http: 8080
port_forward_https: 8443

# Phase 2: Platform Services Configuration

# External DNS Configuration (for automatic DNS management)
external_dns_version: "1.15.0"
external_dns_namespace: "external-dns"
external_dns_provider: "cloudflare"  # Can be changed based on your DNS provider

# Longhorn Storage Configuration
longhorn_version: "1.7.2"
longhorn_namespace: "longhorn-system"
longhorn_storage_class: "longhorn"
longhorn_replica_count: 1  # Single node setup

# Keycloak Configuration
keycloak_version: "22.0.0"
keycloak_namespace: "keycloak"
keycloak_realm: "kubernetes"
keycloak_admin_user: "admin"
keycloak_database: "postgresql"
keycloak_domain: "auth.k8s.local"

# Kubernetes Dashboard Configuration
k8s_dashboard_version: "7.5.0"
k8s_dashboard_namespace: "kubernetes-dashboard"
k8s_dashboard_domain: "dashboard.k8s.local"

# RBAC Configuration
rbac_admin_group: "k8s:admins"
rbac_user_group: "k8s:users"
rbac_viewer_group: "k8s:viewers"

# OAuth2 Integration
oauth2_client_id: "kubernetes"
oauth2_client_secret: "kubernetes-dashboard-secret"
oauth2_issuer_url: "https://auth.k8s.local/realms/kubernetes"

# Storage Configuration
default_storage_class: "longhorn"
backup_storage_enabled: true
snapshot_enabled: true
