---
- name: "Install basic packages"
  apt:
    name:
      - curl
      - wget
      - apt-transport-https
      - ca-certificates
      - gnupg
      - software-properties-common
    state: present
    update_cache: yes

- name: "Disable swap"
  shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: "Load kernel modules"
  shell: |
    modprobe overlay
    modprobe br_netfilter
    echo 'overlay' >> /etc/modules-load.d/k8s.conf
    echo 'br_netfilter' >> /etc/modules-load.d/k8s.conf

- name: "Configure sysctl"
  shell: |
    echo 'net.bridge.bridge-nf-call-iptables = 1' >> /etc/sysctl.d/k8s.conf
    echo 'net.bridge.bridge-nf-call-ip6tables = 1' >> /etc/sysctl.d/k8s.conf
    echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.d/k8s.conf
    sysctl --system
