all:
  children:
    k8s_cluster:
      hosts:
        kharrinhao:
          ansible_host: kharrinhao
          ansible_user: jcarvalho
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          # Kubernetes configuration
          k8s_api_server: "https://192.168.70.211:16443"
          k8s_node_ip: "192.168.70.211"
          k8s_cluster_name: "kharrinhao"
    masters:
      hosts:
        kharrinhao: