---
- name: "Phase 1 Step 1 - Install Flannel CNI"
  hosts: k8s_cluster
  become: yes
  gather_facts: no
  
  tasks:
    - name: "Install Flannel CNI"
      include_role:
        name: flannel

---
- name: "Phase 1 Step 2 - Install cert-manager"
  hosts: k8s_cluster
  become: yes
  gather_facts: no
  
  tasks:
    - name: "Install cert-manager"
      include_role:
        name: cert-manager

---
- name: "Phase 1 Step 3 - Install Ingress NGINX"
  hosts: k8s_cluster
  become: yes
  gather_facts: no
  
  tasks:
    - name: "Install Ingress NGINX"
      include_role:
        name: ingress-nginx

---
- name: "Phase 1 Step 4 - Validation"
  hosts: k8s_cluster
  become: yes
  gather_facts: no
  
  tasks:
    - name: "Run validation"
      include_role:
        name: phase1-validation
